# Generated by Django 2.1.5 on 2019-03-03 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190302_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_page',
            field=models.CharField(blank=True, max_length=128, verbose_name='VK Page'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 3, 19, 32, 14062, tzinfo=utc)),
        ),
    ]
